In [113]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer,MissingIndicator,KNNImputer
from sklearn.metrics import accuracy_score

In [121]:
df=pd.read_csv('/content/train (3).csv')[['Age','Pclass','Fare','Survived']]

In [122]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [123]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [124]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [125]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [126]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [128]:
X_train

      Age  Pclass      Fare
30   40.0       1   27.7208
10    4.0       3   16.7000
873  47.0       3    9.0000
182   9.0       3   31.3875
876  20.0       3    9.8458
..    ...     ...       ...
534  30.0       3    8.6625
584   NaN       3    8.7125
493  71.0       1   49.5042
527   NaN       1  221.7792
168   NaN       1   25.9250

[712 rows x 3 columns]

In [131]:
knn=KNNImputer()
X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [132]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

      Age  Pclass      Fare
0    40.0     1.0   27.7208
1     4.0     3.0   16.7000
2    47.0     3.0    9.0000
3     9.0     3.0   31.3875
4    20.0     3.0    9.8458
..    ...     ...       ...
707  30.0     3.0    8.6625
708  24.2     3.0    8.7125
709  71.0     1.0   49.5042
710  28.0     1.0  221.7792
711  42.8     1.0   25.9250

[712 rows x 3 columns]