In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv('/content/customer (1).csv')

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [8]:
df.size

250

In [9]:
df.iloc[:,2:] #Since only review education and purchased follow or reflect some relation thats why we re allocate df in dataset

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [10]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,2:4],df.iloc[:,-1],test_size=0.2)

In [18]:
X_train

     review education
18     Good    School
11     Good        UG
0   Average    School
8   Average        UG
35     Poor    School
17     Poor        UG
13  Average    School
23     Good    School
44  Average        UG
6      Good    School
48     Good        UG
45     Poor        PG
49     Good        UG
19     Poor        PG
12     Poor    School
38     Good    School
37  Average        PG
32  Average        UG
14     Poor        PG
43     Poor        PG
4   Average        UG
16     Poor        UG
47     Good        PG
42     Good        PG
15     Poor        UG
10     Good        UG
7      Poor    School
31     Poor    School
36     Good        UG
9      Good        UG
33     Good        PG
39     Poor        PG
1      Poor        UG
25     Good    School
27     Poor        PG
30  Average        UG
28     Poor    School
24  Average        PG
41     Good        PG
29  Average        UG

In [20]:
y_train

18     No
11    Yes
0      No
8      No
35    Yes
17    Yes
13     No
23     No
44     No
6      No
48    Yes
45    Yes
49     No
19    Yes
12     No
38     No
37    Yes
32    Yes
14    Yes
43     No
4      No
16    Yes
47    Yes
42    Yes
15     No
10    Yes
7     Yes
31    Yes
36    Yes
9     Yes
33    Yes
39     No
1      No
25     No
27     No
30     No
28     No
24    Yes
41    Yes
29    Yes
Name: purchased, dtype: object

In [21]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
X_train=oe.fit_transform(X_train);
X_test=oe.transform(X_test)

In [22]:
X_train

array([[1., 1.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 0.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 1.],
       [1., 2.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.]])

In [23]:
X_train=pd.DataFrame(X_train,columns=['Education','Review'])
X_test=pd.DataFrame(X_test,columns=['Education','Review'])

In [24]:
X_train

    Education  Review
0         1.0     1.0
1         1.0     2.0
2         0.0     1.0
3         0.0     2.0
4         2.0     1.0
5         2.0     2.0
6         0.0     1.0
7         1.0     1.0
8         0.0     2.0
9         1.0     1.0
10        1.0     2.0
11        2.0     0.0
12        1.0     2.0
13        2.0     0.0
14        2.0     1.0
15        1.0     1.0
16        0.0     0.0
17        0.0     2.0
18        2.0     0.0
19        2.0     0.0
20        0.0     2.0
21        2.0     2.0
22        1.0     0.0
23        1.0     0.0
24        2.0     2.0
25        1.0     2.0
26        2.0     1.0
27        2.0     1.0
28        1.0     2.0
29        1.0     2.0
30        1.0     0.0
31        2.0     0.0
32        2.0     2.0
33        1.0     1.0
34        2.0     0.0
35        0.0     2.0
36        2.0     1.0
37        0.0     0.0
38        1.0     0.0
39        0.0     2.0

In [26]:
#SINCE MY OUTPUT COLUMN IS CATEGORICAL THAT IS WHY NOW WE USE LABEL ENCODER

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

In [28]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [29]:
y_train=pd.DataFrame(y_train,columns=['Purchased'])
y_test=pd.DataFrame(y_test,columns=['Purchased'])

In [30]:
y_train

    Purchased
0           0
1           1
2           0
3           0
4           1
5           1
6           0
7           0
8           0
9           0
10          1
11          1
12          0
13          1
14          0
15          0
16          1
17          1
18          1
19          0
20          0
21          1
22          1
23          1
24          0
25          1
26          1
27          1
28          1
29          1
30          1
31          0
32          0
33          0
34          0
35          0
36          0
37          1
38          1
39          1